### ISSUE TITLE
customize.php broken after fresh wordpress install (v5.9.3)

### ISSUE THREAD

**Issue by Bernhard-Huber** [kenzap/myticket-events#16]
Hello,

the mytickets-events plugin seems to prevent customizer.php from loading on the latest wordpress release.
testing scenario:
- fresh v5.9.3wordpress install without any themes and other plugins.
- customizer.php is loading perfectly fine when the mytickets-events plugin is deactivated
- customizer.php does not load when mytickets-events plugin is activated.
- tested with firefox 99.0.1, edge 100.0.1185.50, google chrome 101.0.4951.41
![grafik](https://user-images.githubusercontent.com/76926979/165837445-6feca1d3-afe1-4fed-a458-6d34ae528340.png)

i was not able to find the issue myself yet but i am plannig to dig into it on the weekend.
br,

**Comment by kenzap** [comment]
Try updating from the following source: https://drive.google.com/file/d/1nI9_2T6YEQbXDN4J-VQZ9aEFRWYO61Q9/view?usp=sharing

This release will be officially rolled out soon.
